services:
  app:
    image: clinical-web-app

    build:
      context: .
      dockerfile: Dockerfile.azure

    container_name: clinical-web-app

    restart: unless-stopped

    env_file:
      - .env.development

    ports:
      - "80:80"

    networks:
      - azure-network

networks:
  azure-network:
    driver: bridge